// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Desafio_Amcom.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Testes de Validação do Formulário 1")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class TestesDeValidacaoDoFormulario1Feature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("pt-br"), "Features", "Testes de Validação do Formulário 1", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "Formulario1.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Formulario1.feature.ndjson", 12);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Enviar o formulário 1 com sucesso preenchendo todos os campos obrigatórios")]
        [global::NUnit.Framework.CategoryAttribute("CenarioFeliz")]
        public async global::System.Threading.Tasks.Task EnviarOFormulario1ComSucessoPreenchendoTodosOsCamposObrigatorios()
        {
            string[] tagsOfScenario = new string[] {
                    "CenarioFeliz"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Enviar o formulário 1 com sucesso preenchendo todos os campos obrigatórios", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
    await testRunner.GivenAsync("que eu acessei a página de formulários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 7
    await testRunner.WhenAsync("preencho o nome \"João\", sobrenome \"Silva\" e telefone \"11999998888\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 8
    await testRunner.AndAsync("clico no botão \"Enviar\" do Formulário 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 9
    await testRunner.ThenAsync("o modal deve ser exibido com a mensagem \"Enviado com sucesso!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
#line 10
    await testRunner.WhenAsync("clico no botão de fechar do modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 11
    await testRunner.ThenAsync("o modal deve desaparecer da tela", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Tentar enviar o formulário sem preencher os campos obrigatórios")]
        [global::NUnit.Framework.CategoryAttribute("BugConhecido")]
        public async global::System.Threading.Tasks.Task TentarEnviarOFormularioSemPreencherOsCamposObrigatorios()
        {
            string[] tagsOfScenario = new string[] {
                    "BugConhecido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Tentar enviar o formulário sem preencher os campos obrigatórios", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que eu acessei a página de formulários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("não preencho nenhum campo do Formulário 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 17
    await testRunner.AndAsync("clico no botão \"Enviar\" do Formulário 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 18
    await testRunner.ThenAsync("o modal com a mensagem de sucesso não deve ser exibido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar restrições de caracteres nos campos de nome e sobrenome")]
        [global::NUnit.Framework.CategoryAttribute("ValidacaoCampos")]
        [global::NUnit.Framework.CategoryAttribute("BugConhecido")]
        [global::NUnit.Framework.TestCaseAttribute("Raul123", "Silv4", "2", null)]
        [global::NUnit.Framework.TestCaseAttribute("J@oão", "M_endes", "3", null)]
        [global::NUnit.Framework.TestCaseAttribute("99999", "88888", "4", null)]
        public async global::System.Threading.Tasks.Task ValidarRestricoesDeCaracteresNosCamposDeNomeESobrenome(string nome, string sobrenome, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ValidacaoCampos",
                    "BugConhecido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Nome", nome);
            argumentsOfScenario.Add("Sobrenome", sobrenome);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar restrições de caracteres nos campos de nome e sobrenome", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("que eu acessei a página de formulários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 23
    await testRunner.WhenAsync(string.Format("preencho o nome \"{0}\", sobrenome \"{1}\" e telefone \"11999998888\"", nome, sobrenome), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 24
    await testRunner.AndAsync("clico no botão \"Enviar\" do Formulário 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 25
    await testRunner.ThenAsync("o modal com a mensagem de sucesso não deve ser exibido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar formatos inválidos e letras no campo telefone")]
        [global::NUnit.Framework.CategoryAttribute("ValidacaoCampos")]
        [global::NUnit.Framework.CategoryAttribute("BugConhecido")]
        [global::NUnit.Framework.TestCaseAttribute("OnzeNoveOitoOito", "5", null)]
        [global::NUnit.Framework.TestCaseAttribute("119abcdefff", "6", null)]
        [global::NUnit.Framework.TestCaseAttribute("(11)9999999999999", "7", null)]
        [global::NUnit.Framework.TestCaseAttribute("123", "8", null)]
        public async global::System.Threading.Tasks.Task ValidarFormatosInvalidosELetrasNoCampoTelefone(string telefone, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ValidacaoCampos",
                    "BugConhecido"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Telefone", telefone);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar formatos inválidos e letras no campo telefone", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 35
    await testRunner.GivenAsync("que eu acessei a página de formulários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 36
    await testRunner.WhenAsync(string.Format("preencho o nome \"Raul\", sobrenome \"Silveira\" e telefone \"{0}\"", telefone), ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 37
    await testRunner.AndAsync("clico no botão \"Enviar\" do Formulário 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "E ");
#line hidden
#line 38
    await testRunner.ThenAsync("o modal com a mensagem de sucesso não deve ser exibido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Validar alertas visuais de campos obrigatórios ao perder o foco")]
        [global::NUnit.Framework.CategoryAttribute("ValidacaoVisual")]
        [global::NUnit.Framework.CategoryAttribute("BugConhecido")]
        public async global::System.Threading.Tasks.Task ValidarAlertasVisuaisDeCamposObrigatoriosAoPerderOFoco()
        {
            string[] tagsOfScenario = new string[] {
                    "ValidacaoVisual",
                    "BugConhecido"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Validar alertas visuais de campos obrigatórios ao perder o foco", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
    await testRunner.GivenAsync("que eu acessei a página de formulários", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 50
    await testRunner.WhenAsync("eu clico no campo de nome e mudo para o campo de sobrenome sem preencher", ((string)(null)), ((global::Reqnroll.Table)(null)), "Quando ");
#line hidden
#line 51
    await testRunner.ThenAsync("o campo de nome deve exibir um alerta visual de erro ou borda vermelha", ((string)(null)), ((global::Reqnroll.Table)(null)), "Então ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
